version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu

# cache:
#  - ui\node_modules
#  - electron-app\node_modules
#  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - sh: nvm install lts
  - sh: nvm use lts
  - yarn

build_script:
  - sh: yarn release:linux

test: off
