name: Build/Release
on:
  push:
    branches:
      - 'master'
      - 'develop'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 16

        # Note: These flags needed to speed up build
      - name: Install dependencies
        run: npm install --frozen-lockfile --prefer-offline

      - name: Build dependencies
        run: npm run make

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ github.ref == 'refs/heads/master' }}
          skip-build: true
          app_root: 'electron-app'
